### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by AkBappy** [OSGP/Documentation#195]
After setting the environment, when I start the tomcat server, I get null pointer exception.

[2018-08-28 06:40:59.267] [dev-XPS-13-9360] [pool-14-thread-1] INFO o.o.s.p.iec61850.server.RtuSimulator@generateData:459 - Exception while generating values.
java.lang.NullPointerException: null
	at org.opensmartgridplatform.simulator.protocol.iec61850.server.logicaldevices.LogicalDevice.setRandomInt(LogicalDevice.java:149)
	at org.opensmartgridplatform.simulator.protocol.iec61850.server.logicaldevices.Battery.getAttributesAndSetValues(Battery.java:112)
	at org.opensmartgridplatform.simulator.protocol.iec61850.server.RtuSimulator.generateData(RtuSimulator.java:457)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Sander3003** [comment]
Thank you for the report, the developers are currently busy, they will reply later.

**Comment by kevinsmeets** [comment]
@AkBappy, thank you for reporting this issue. We are already aware of this situation (for our own reference, see task ZS-220). This null pointer exception should not be a problem for you as there is very little functionality that relies on the IEC61850 simulator.
